### PR TITLE
Create hardware.md

### LINKED ISSUE #2: Make List of Available Bare Metal Systems
Considering how many folks have bare metal and resources to offer, let's get started by looking at and catalogging what kind of bare metal compute we could leverage if needed.

### PR DESCRIPTION
**Pull request by TheGuyDanish**
Creates hardware.md for tracking current and available hardware, fixes #2

### CODE REVIEW

**Comment by madmax-codewarrior-0** [comment]
@TheGuyDanish 
Do we think it'd be best to put this in a sub-folder structure for better organization, and add a little more detail? Suggestion: `docs/compute/unused-baremetal-servers.md`

I think at some point this repo could get pretty extensive, even if it's "just operations". Having the folder structure like `docs` will keep this separated from `ansible-playbooks` for example (if we go that route for something), and the details in the name will distinguish it from other hardware, like `running-baremetal-servers.md`.

**Comment by TheGuyDanish** [comment]
`docs/compute/unused-baremetal-servers.md` feels a little overkill to me, at least at the moment. Plus it can be renamed, moved and still tracked.

I'm definitely in favor of moving it to say `docs/hardware-overview.md`, as it contains all hardware, not just unused.

**Comment by madmax-codewarrior-0** [comment]
> it can be renamed, moved and still tracked.

Good point!

> moving it to say `docs/hardware-overview.md`, as it contains all hardware, not just unused.

Agreed. We can then slap labels or attributes on each documented system as to it's purpose, whether that's "collect dust" or "route grapher". :+1:

**Comment by TheGuyDanish** [comment]
Updated. Let me know if you wanna slap a label on Morris now or save that for a later date.

**Comment by madmax-codewarrior-0** [comment]
> slap a label on Morris now or save that for a later date.

Let's save it for another time, when we know more about how the systems will be used.

**Review by madmax-codewarrior-0 — APPROVED** [review]

**Review by pveeckhout — APPROVED** [review]

**Pull request merged**
